M48
; DRILL file {KiCad 7.0.10} date Mon Jan 15 20:07:17 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-15T20:07:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X92.36Y-29.783
X98.14Y-29.783
T2
X105.188Y-44.259
X106.204Y-36.639
X107.22Y-44.259
M30
